# Site settings
title: Wells Fargo / Maker Lab
email: carson@metapattern.is
description: Welcome to the Wells Fargo Maker Lab.
destination: welcome
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: metapattern
github_username:  cbowley

# Build settings
markdown: kramdown