# Site settings
title: Thync / Vibe Sessions
email: carson@metapattern.is
description: Welcome to the Thync Vibe Sessions.
destination: welcome
baseurl: "/thync/welcome/" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: metapattern
github_username:  cbowley

# Build settings
markdown: kramdown